### ISSUE TITLE
Enhanced profiles search with faceted filters

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#958]
### Search wireframes

https://whimsical.com/5uUECYJe5vvWXZj5M9HDu8

<details>

<summary>screenshot</summary>

![](https://user-images.githubusercontent.com/15908208/93708141-c4ac1980-fb2b-11ea-93bd-b825d4b81cc3.png)

</details>

## TODOs

The remaining tasks to do before the forum announcement:
- [x] show the filters in the url to allow sharing
- [ ] indicate that filtering is active on mobile view (right you can't guess whether you're looking at a filtered view or not)
- [ ] add the map on top
- [x] add algolia logo somewhere and request the open source subscription
- [x] test it on the latest pixel, the latest iphone, mac os safari/firefox/chrome, windows edge/chrome/firefox
    - especially the multi select buttons since we might have downgraded bs3 from 3.4 to 3.3 - eg on the profile `community` field edit

Post forum post:
- [ ] add a `group organizer` field to the filters
- [x] migrate the algolia account to aloglia@eahub.org account
- [ ] improve the styling (navbar, menu, buttons), hopefully with the help of a UX/UI specialist - move it out to another ticket

## Specs

Profile cards:
- Name (link to profile)
- Country, City
- optional - hide or show empty if not specified
    - local group
    - local group user is organiser of
    - organisation affiliation
    - Summary
    - Areas of experties
    - cause areas

### Filters
- checkboxes (icons)
	- available as speaker
	- available as employee
	- available as volunteer
	- is group organiser
- combined with "AND" logic: if I select "available as speaker" and "group organisers" and "London" - I only get group organisers that are available as speakers in London

**Comment by vagarwalla** [comment]
Here's the first mockup of the new profiles page : 
https://whimsical.com/5uUECYJe5vvWXZj5M9HDu8 (See the white box with Issue #958)


The new profile page will be the have the following columns:
- Full Name (hyperlinked with the user profile)
- City
- Country
- Local Group
- Cause Area
- Area of expertise

And there will be filters for each column like in Excel. The filters should also be additive - e.g. you can filter 1 column and another column at the same time.

**Comment by vagarwalla** [comment]
Updates on functionality & Discussion:

- We are going with Option 2
- The search box will limit results by profile (e.g. if you pick country UK then all the other filters will only search within the UK profiles)
- The text search will search all available fields in the profile (whether they display in the search or not)

**Comment by sebgrebe** [comment]
Wireframe #1  
![image](https://user-images.githubusercontent.com/15908208/93708141-c4ac1980-fb2b-11ea-93bd-b825d4b81cc3.png)

**Comment by sebgrebe** [comment]
Wireframe: Expanded view  
![image](https://user-images.githubusercontent.com/15908208/93708152-dd1c3400-fb2b-11ea-99bb-3fe7b1c043c8.png)

**Comment by sebgrebe** [comment]
### Tool decision   

We are currently using [datatables](https://datatables.net/) for displaying the table. With the new filtering envisioned, we want to reasses whether datatables is the best solution or whether we'd like to move to another tool.  

[AG Grid](https://www.ag-grid.com/) has been recommended to me by someone at work.  

Risks of moving to another tool: 
- Accidentally breaking existing functionality  
- time sink, might take much longer than expected  

To be discussed with @victor-yunenko

**Comment by victor-yunenko** [comment]
Hi @vagarwalla, would you be able to add me (victor.yunenko@gmail.com) to the whimsical document?

**Comment by victor-yunenko** [comment]
Technical update:
- from [the documentation](https://www.algolia.com/doc/guides/managing-results/refine-results/faceting/?language=python) algolia faceted search appears to be quite suitable, I'll start trying to integrate it - I already created an account and sent out the invites to Sebastian, Michal and Vaidehi
- for the frontend it seems that vue.js + typescript is going to be a good fit, I'll be working with it for the time being unless anyone has any objections 👌

**Comment by victor-yunenko** [comment]
I looked through the tickets related to the search - the description was quite detailed which is great 👍  - having the search description being split on 5 tickets confused me a bit though 😅 

I combined the 5 descriptions into one and then started removing the duplicated lines or information that would be the default behavior (eg the reset of results after unselecting boxes/dropdown). The result I added to this ticket's description - would it be ok with everyone if I close #969, #972, #974 and #975 in favour for this ticket?

**Comment by victor-yunenko** [comment]
Update:

Aloglia faceted filters look quite great, the backend is already testable here: https://www.algolia.com/apps/PFD0UVG9YB/explorer/browse/profiles

<details>

<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/36416236/94343802-68f9f880-0023-11eb-9307-24300e52cf3a.png)

</details>

**Comment by victor-yunenko** [comment]
Update: 

So far the intermediate result looks rather satisfying - https://drive.google.com/file/d/1GGkj9ID4TgGLiMGrUovoUmm-UTfukwbP/view

I would let everyone try it out, but we don't have a stage server ;)

**Comment by victor-yunenko** [comment]
Hi @vagarwalla, regarding the following issue that you had:

> - I searched for career interest area "Research" & "Government & Policy" and Local groups: "Singapore"
> - This is filter people who meet all the criteria
> - I get 2 results: Rebecca & Vaidehi
> - BUT when I remove the filter "Government & Policy" it says "No results found". When instead it should show me candidates who match "Research" & "effective altruism singapore"
> - When I redo the search starting with these two terms Rebecca & Vaidehi appear again

I was able to reproduce it before, but not anymore, could you confirm whether the issue persists? FYI I'm testing on https://eahub-stage.us.aldryn.io/profiles/

**Comment by victor-yunenko** [comment]
> I don't think it should search the exact word "mother", but open to other thoughts on this if there is a benefit to showing these other terms. i imagine it would be annoying to find a bunch of search results with words that don't really match the searchers' original phrase.

@vagarwalla I would say the typo-tolerance is a desirable behavior. Basically if I disable it then people who search for `effetcive altruism` wouldn't be able to see the results as `effective altruism`. Does that make sense to you?

**Comment by victor-yunenko** [comment]
FYI the typos are of course presented below the normal search results and usually visible only when nothing else was found👌

**Comment by victor-yunenko** [comment]
@vagarwalla, @sebgrebe, it appears that we might not need those buttons anymore, since they're either part of the navbar or the search filters?

I think if we have data from GA regarding which of those buttons are used most often we can refactor them into something more similar to CTAs?

![image](https://user-images.githubusercontent.com/36416236/97107874-7bbf2600-16d2-11eb-8053-268da8e457ab.png)

**Comment by vagarwalla** [comment]
> @vagarwalla I would say the typo-tolerance is a desirable behavior. Basically if I disable it then people who search for effetcive altruism wouldn't be able to see the results as effective altruism. Does that make sense to you?

Okay, let's leave it in for now!

**Comment by vagarwalla** [comment]
> @vagarwalla, @sebgrebe, it appears that we might not need those buttons anymore, since they're either part of the navbar or the search filters?
> 
> I think if we have data from GA regarding which of those buttons are used most often we can refactor them into something more similar to CTAs?
> 
> ![image](https://user-images.githubusercontent.com/36416236/97107874-7bbf2600-16d2-11eb-8053-268da8e457ab.png)

Just checked and the views are very low - just 5-22 views in the last 1 year. I think if we just have the filter that should be enough for now? And we can think about reintroducing the buttons at a later date?

**Comment by vagarwalla** [comment]
> Hi @vagarwalla, regarding the following issue that you had:
> 
> > * I searched for career interest area "Research" & "Government & Policy" and Local groups: "Singapore"
> > * This is filter people who meet all the criteria
> > * I get 2 results: Rebecca & Vaidehi
> > * BUT when I remove the filter "Government & Policy" it says "No results found". When instead it should show me candidates who match "Research" & "effective altruism singapore"
> > * When I redo the search starting with these two terms Rebecca & Vaidehi appear again
> 
> I was able to reproduce it before, but not anymore, could you confirm whether the issue persists? FYI I'm testing on https://eahub-stage.us.aldryn.io/profiles/

I just checked again on that server and I couldn't recreate the bug! So it looks like it's been fixed?

**Comment by victor-yunenko** [comment]
- indicate that filtering is active on mobile view (right you can't guess whether you're looking at a filtered view or not)
- show the filters in the url to allow sharing
- add the map on top
- improve the styling (navbar, menu, buttons)

**Comment by sebgrebe** [comment]
Can we close this ticket and add new ones for any further improvements and bug fixes to make progress on this more transparent? @victor-yunenko @vagarwalla?

**Comment by victor-yunenko** [comment]
Sounds good to me, I added the remaining points to #1064  👍
